<?php
  /*
    Simple Link Tracker Configuration. https://marcosraudkett.com/
    Generated by Installer.
  */


    /* MySQL Database Hostname */   $db_host  = '';
    /* MySQL Database Name */       $db_name  = '';
    /* MySQL Database Username */   $db_user  = '';
    /* MySQL Database Password */   $db_pass  = '';  
                    

                      //Your full domain: http://mydomain.com/ ex: "http://mvrclabs.info/"
                      $myhost   = 'http://mvrclabs.info/';              
                      //Root App Path that comes after above domain. ex: "linktracker/"
                      $app_path = 'linktracker/';                     

?>
